### ISSUE TITLE
how to install requirements.txt on colab?

### ISSUE THREAD

**Issue by srn-source** [xfactlab/orpo#12] opened 2024-04-03 07:33 UTC
I am using pip install -r requirements.txt but its error. and first time that i see 
 file:///home/conda/feedstock_root/build_artifacts/accelerate_1710334587919/work 

what does it mean?

**Comment by jiwooya1000** [comment] 2024-04-03 10:02
Hello @srn-source, 
It seems like the problem is caused by installing `accelerate`.
Could you try installing `accelerate` first before `pip install -r requirements.txt`?

**Comment by srn-source** [comment] 2024-04-06 13:30
@jiwooya1000  Not working  but  after i remove @ file:///...... every library. It is working.

**Comment by jiwooya1000** [comment] 2024-04-08 12:38
Good to hear that it is working now! Maybe it is due to the difference coming from Colab environment. Closing the issue as it is resolved👍 Please feel free to open it again if you have further problems related to this

**Closed by jiwooya1000** 2024-04-08 12:38 UTC
